FROM python:3.11-slim

WORKDIR /app

COPY pyproject.toml ./
COPY app ./app
COPY alembic.ini ./
COPY alembic ./alembic

RUN pip install --no-cache-dir -e .[dev]

CMD ["uvicorn", "app.entry:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
