"""initial

Revision ID: ca363b702936
Revises: 
Create Date: 2026-06-10 13:19:02.633885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca363b702936'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'name', name='uq_entity_type_name')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('adapter', sa.String(length=100), nullable=True),
    sa.Column('stream', sa.String(length=20), nullable=False),
    sa.Column('vendor', sa.String(length=50), nullable=True),
    sa.Column('fetch_cron', sa.String(length=100), nullable=True),
    sa.Column('main_category', sa.String(length=100), nullable=True),
    sa.Column('relevance_filter', sa.Boolean(), nullable=False),
    sa.Column('relevance_keywords', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('health_status', sa.String(length=20), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('last_content_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'kind', name='uq_tag_name_kind')
    )
    op.create_table('compatibility_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.String(length=50), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('product', sa.String(length=200), nullable=True),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('arch', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor', 'kind', 'name', 'product', 'version', 'arch', name='uq_compat')
    )
    op.create_index(op.f('ix_compatibility_entries_kind'), 'compatibility_entries', ['kind'], unique=False)
    op.create_index(op.f('ix_compatibility_entries_vendor'), 'compatibility_entries', ['vendor'], unique=False)
    op.create_table('image_releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.String(length=50), nullable=False),
    sa.Column('product', sa.String(length=200), nullable=False),
    sa.Column('image_tag', sa.String(length=200), nullable=False),
    sa.Column('arch', sa.String(length=50), nullable=True),
    sa.Column('cloud', sa.String(length=50), nullable=True),
    sa.Column('image_id', sa.String(length=300), nullable=True),
    sa.Column('checksum', sa.String(length=200), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor', 'product', 'image_tag', 'arch', 'cloud', name='uq_img')
    )
    op.create_index(op.f('ix_image_releases_vendor'), 'image_releases', ['vendor'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('clean_content', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('main_category', sa.String(length=100), nullable=True),
    sa.Column('title_tldr', sa.String(length=200), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_points', sa.JSON(), nullable=True),
    sa.Column('info_type', sa.String(length=20), nullable=True),
    sa.Column('importance', sa.String(length=10), nullable=True),
    sa.Column('why_it_matters', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('llm_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_content_hash'), 'items', ['content_hash'], unique=False)
    op.create_index(op.f('ix_items_importance'), 'items', ['importance'], unique=False)
    op.create_index(op.f('ix_items_info_type'), 'items', ['info_type'], unique=False)
    op.create_index(op.f('ix_items_main_category'), 'items', ['main_category'], unique=False)
    op.create_index(op.f('ix_items_published_at'), 'items', ['published_at'], unique=False)
    op.create_index(op.f('ix_items_status'), 'items', ['status'], unique=False)
    op.create_index(op.f('ix_items_url_hash'), 'items', ['url_hash'], unique=True)
    op.create_table('product_lifecycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.String(length=50), nullable=False),
    sa.Column('product', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('ga_date', sa.DateTime(), nullable=True),
    sa.Column('eol_date', sa.DateTime(), nullable=True),
    sa.Column('eus_date', sa.DateTime(), nullable=True),
    sa.Column('phase', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor', 'product', 'version', name='uq_lc_vpv')
    )
    op.create_index(op.f('ix_product_lifecycles_eol_date'), 'product_lifecycles', ['eol_date'], unique=False)
    op.create_index(op.f('ix_product_lifecycles_vendor'), 'product_lifecycles', ['vendor'], unique=False)
    op.create_table('security_advisories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.String(length=50), nullable=False),
    sa.Column('advisory_id', sa.String(length=100), nullable=False),
    sa.Column('cve_ids', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('affected_products', sa.JSON(), nullable=True),
    sa.Column('fixed_versions', sa.JSON(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor', 'advisory_id', name='uq_adv_vendor_id')
    )
    op.create_index(op.f('ix_security_advisories_published_at'), 'security_advisories', ['published_at'], unique=False)
    op.create_index(op.f('ix_security_advisories_severity'), 'security_advisories', ['severity'], unique=False)
    op.create_index(op.f('ix_security_advisories_vendor'), 'security_advisories', ['vendor'], unique=False)
    op.create_table('item_entities',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'entity_id')
    )
    op.create_table('item_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_tags',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_tags')
    op.drop_table('item_sources')
    op.drop_table('item_entities')
    op.drop_index(op.f('ix_security_advisories_vendor'), table_name='security_advisories')
    op.drop_index(op.f('ix_security_advisories_severity'), table_name='security_advisories')
    op.drop_index(op.f('ix_security_advisories_published_at'), table_name='security_advisories')
    op.drop_table('security_advisories')
    op.drop_index(op.f('ix_product_lifecycles_vendor'), table_name='product_lifecycles')
    op.drop_index(op.f('ix_product_lifecycles_eol_date'), table_name='product_lifecycles')
    op.drop_table('product_lifecycles')
    op.drop_index(op.f('ix_items_url_hash'), table_name='items')
    op.drop_index(op.f('ix_items_status'), table_name='items')
    op.drop_index(op.f('ix_items_published_at'), table_name='items')
    op.drop_index(op.f('ix_items_main_category'), table_name='items')
    op.drop_index(op.f('ix_items_info_type'), table_name='items')
    op.drop_index(op.f('ix_items_importance'), table_name='items')
    op.drop_index(op.f('ix_items_content_hash'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_image_releases_vendor'), table_name='image_releases')
    op.drop_table('image_releases')
    op.drop_index(op.f('ix_compatibility_entries_vendor'), table_name='compatibility_entries')
    op.drop_index(op.f('ix_compatibility_entries_kind'), table_name='compatibility_entries')
    op.drop_table('compatibility_entries')
    op.drop_table('tags')
    op.drop_table('sources')
    op.drop_table('entities')
    # ### end Alembic commands ###
