"""add_v2_tables

Revision ID: cb7dd0a4d986
Revises: 1c0d648eb814
Create Date: 2026-06-15 17:28:15.591348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb7dd0a4d986'
down_revision: Union[str, Sequence[str], None] = '1c0d648eb814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('agent_crawl_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('plan_urls_count', sa.Integer(), nullable=False),
    sa.Column('fetched_count', sa.Integer(), nullable=False),
    sa.Column('quality_passed', sa.Integer(), nullable=False),
    sa.Column('items_created', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_site_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('url_pattern', sa.String(length=2000), nullable=False),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('quality_reason', sa.Text(), nullable=True),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('relevant_topic', sa.String(length=200), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('seen_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'url_pattern', name='uq_agent_memory_source_url')
    )
    op.create_table('agent_source_configs',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('focus_areas', sa.JSON(), nullable=False),
    sa.Column('topic_groups', sa.JSON(), nullable=False),
    sa.Column('crawl_depth', sa.Integer(), nullable=False),
    sa.Column('max_urls_per_run', sa.Integer(), nullable=False),
    sa.Column('quality_threshold', sa.Integer(), nullable=False),
    sa.Column('crawl_workers', sa.Integer(), nullable=False),
    sa.Column('quality_workers', sa.Integer(), nullable=False),
    sa.Column('summary_workers', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('digests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('time_range_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_range_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('period_summary', sa.Text(), nullable=True),
    sa.Column('hotspots', sa.JSON(), nullable=False),
    sa.Column('emerging_topics', sa.JSON(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('free_text_description', sa.Text(), nullable=True),
    sa.Column('enable_llm_scoring', sa.Boolean(), nullable=False),
    sa.Column('min_score_threshold', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_item_interactions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('interacted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'item_id', 'action')
    )
    op.create_table('user_item_scores',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('scoring_method', sa.String(length=20), nullable=False),
    sa.Column('score_reason', sa.Text(), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'item_id')
    )
    op.create_unique_constraint('uq_item_source_url', 'item_sources', ['item_id', 'source_id', 'url'])
    op.add_column('sources', sa.Column('link_selector', sa.String(length=500), nullable=True))
    op.add_column('sources', sa.Column('title_selector', sa.String(length=500), nullable=True))
    op.add_column('sources', sa.Column('date_selector', sa.String(length=500), nullable=True))
    op.add_column('sources', sa.Column('stealth', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'stealth')
    op.drop_column('sources', 'date_selector')
    op.drop_column('sources', 'title_selector')
    op.drop_column('sources', 'link_selector')
    op.drop_constraint('uq_item_source_url', 'item_sources', type_='unique')
    op.drop_table('user_item_scores')
    op.drop_table('user_item_interactions')
    op.drop_table('user_profiles')
    op.drop_table('digests')
    op.drop_table('agent_source_configs')
    op.drop_table('agent_site_memory')
    op.drop_table('agent_crawl_runs')
    op.drop_table('users')
    # ### end Alembic commands ###
