import type { Facets, ItemDetail } from "./types";

export const demoItems: ItemDetail[] = [
  {
    id: 1001,
    title: "Kernel scheduler update improves mixed workload latency",
    title_tldr: "内核调度更新降低混合负载延迟",
    main_category: "OS性能发展",
    info_type: "性能数据",
    importance: "高",
    published_at: "2026-06-10T09:00:00Z",
    fetched_at: "2026-06-10T09:05:00Z",
    url: "https://example.com/kernel-scheduler-update",
    summary: "新一轮调度器优化在 CPU 密集与 IO 密集任务混跑时改善了尾延迟表现。",
    key_points: [
      "混合负载下 P99 延迟下降约 18%",
      "变更集中在 task placement 和 wakeup path",
      "对通用服务型节点更有参考价值",
    ],
    why_it_matters: "这类更新通常会直接影响线上主机在高峰期的稳定性和资源利用率。",
    llm_confidence: 0.93,
    sub_tags: ["kernel", "scheduler", "latency"],
    entities: [{ type: "os", name: "Linux" }, { type: "topic", name: "Kernel Scheduler" }],
    source_links: [{ source_id: 1, url: "https://example.com/kernel-scheduler-update" }],
  },
  {
    id: 1002,
    title: "Ubuntu publishes new security advisory for OpenSSL",
    title_tldr: "Ubuntu 发布 OpenSSL 安全公告",
    main_category: "OS跟踪来源",
    info_type: "更新",
    importance: "高",
    published_at: "2026-06-09T05:30:00Z",
    fetched_at: "2026-06-09T05:35:00Z",
    url: "https://example.com/ubuntu-openssl-advisory",
    summary: "Ubuntu 更新了 OpenSSL 相关安全公告，修复多个影响服务端连接处理的问题。",
    key_points: [
      "影响范围覆盖长期支持版本",
      "官方给出对应修复包版本",
      "建议优先检查对外服务节点",
    ],
    why_it_matters: "安全公告对运维排期和漏洞响应优先级有直接影响。",
    llm_confidence: 0.95,
    sub_tags: ["security", "openssl"],
    entities: [{ type: "vendor", name: "Ubuntu" }, { type: "package", name: "OpenSSL" }],
    source_links: [{ source_id: 2, url: "https://example.com/ubuntu-openssl-advisory" }],
  },
  {
    id: 1003,
    title: "OpenCloudOS adds compatibility notes for container runtime stack",
    title_tldr: "OpenCloudOS 补充容器运行时适配说明",
    main_category: "软件包适配",
    info_type: "适配",
    importance: "中",
    published_at: "2026-06-08T03:00:00Z",
    fetched_at: "2026-06-08T03:05:00Z",
    url: "https://example.com/opencloudos-runtime-compat",
    summary: "新增了容器运行时与若干内核版本组合下的兼容性说明，覆盖常见部署方式。",
    key_points: [
      "明确了支持的 runtime 版本范围",
      "给出了已知限制项",
      "适合整理为兼容性知识库条目",
    ],
    why_it_matters: "兼容性说明能减少升级时的试错成本，也方便判断是否需要额外回归测试。",
    llm_confidence: 0.88,
    sub_tags: ["container", "compatibility"],
    entities: [{ type: "vendor", name: "OpenCloudOS" }, { type: "product", name: "container runtime" }],
    source_links: [{ source_id: 3, url: "https://example.com/opencloudos-runtime-compat" }],
  },
  {
    id: 1004,
    title: "Internal AI assistant expands release-note triage workflow",
    title_tldr: "司内 AI 工具扩展 release note 初筛流程",
    main_category: "司内AI工具",
    info_type: "观点/分析",
    importance: "中",
    published_at: "2026-06-07T11:20:00Z",
    fetched_at: "2026-06-07T11:25:00Z",
    url: "https://example.com/internal-ai-triage",
    summary: "团队分享了把司内 AI 工具接入 release note 初筛的经验，重点是减少人工扫读时间。",
    key_points: [
      "以固定字段输出初筛结果",
      "保留人工复核入口",
      "对周报整理效率提升明显",
    ],
    why_it_matters: "这类经验可以直接复用到情报整理工作流里，帮助团队更快建立稳定流程。",
    llm_confidence: 0.84,
    sub_tags: ["workflow", "release note"],
    entities: [{ type: "topic", name: "AI workflow" }],
    source_links: [{ source_id: 4, url: "https://example.com/internal-ai-triage" }],
  },
];

export const demoFacets: Facets = {
  main_category: [],
  info_type: [],
  importance: [],
};
