import type { Facets, ItemDetail } from "./types";

export const demoItems: ItemDetail[] = [
  {
    id: 1001,
    title: "Kernel scheduler update improves mixed workload latency",
    title_tldr: "内核调度更新降低混合负载延迟",
    main_category: "OS性能发展",
    info_type: "性能数据",
    importance: "高",
    published_at: "2026-06-10T09:00:00Z",
    fetched_at: "2026-06-10T09:05:00Z",
    url: "https://example.com/kernel-scheduler-update",
    summary: "新一轮调度器优化在 CPU 密集与 IO 密集任务混跑时改善了尾延迟表现。",
    key_points: [
      "[延迟] 混合负载下 P99 延迟下降约 18%",
      "[调度] 变更集中在 task placement 和 wakeup path",
      "[适用场景] 对通用服务型节点更有参考价值",
    ],
    llm_confidence: 0.93,
    why_it_matters: "调度尾延迟下降会直接改善混部节点上的服务质量，适合对照当前内核版本评估是否跟进。",
    os_insight: "可关注 wakeup path 与 task placement 的取舍，评估对通用服务节点的可移植性。",
    sub_tags: ["kernel", "scheduler", "latency"],
    source_links: [{ source_id: 1, url: "https://example.com/kernel-scheduler-update" }],
  },
  {
    id: 1002,
    title: "Ubuntu publishes new security advisory for OpenSSL",
    title_tldr: "Ubuntu 发布 OpenSSL 安全公告",
    main_category: "OS跟踪来源",
    info_type: "更新",
    importance: "高",
    published_at: "2026-06-09T05:30:00Z",
    fetched_at: "2026-06-09T05:35:00Z",
    url: "https://example.com/ubuntu-openssl-advisory",
    summary: "Ubuntu 更新了 OpenSSL 相关安全公告，修复多个影响服务端连接处理的问题。",
    key_points: [
      "[影响范围] 覆盖长期支持版本",
      "[修复包] 官方给出对应修复包版本",
      "[处置建议] 建议优先检查对外服务节点",
    ],
    llm_confidence: 0.95,
    sub_tags: ["security", "openssl"],
    source_links: [{ source_id: 2, url: "https://example.com/ubuntu-openssl-advisory" }],
  },
  {
    id: 1003,
    title: "OpenCloudOS adds compatibility notes for container runtime stack",
    title_tldr: "OpenCloudOS 补充容器运行时适配说明",
    main_category: "软件包适配",
    info_type: "适配",
    importance: "中",
    published_at: "2026-06-08T03:00:00Z",
    fetched_at: "2026-06-08T03:05:00Z",
    url: "https://example.com/opencloudos-runtime-compat",
    summary: "新增了容器运行时与若干内核版本组合下的兼容性说明，覆盖常见部署方式。",
    key_points: [
      "[版本范围] 明确了支持的 runtime 版本范围",
      "[限制项] 给出了已知限制项",
      "[知识库] 适合整理为兼容性知识库条目",
    ],
    llm_confidence: 0.88,
    sub_tags: ["container", "compatibility"],
    source_links: [{ source_id: 3, url: "https://example.com/opencloudos-runtime-compat" }],
  },
  {
    id: 1004,
    title: "Internal AI assistant expands release-note triage workflow",
    title_tldr: "司内 AI 工具扩展 release note 初筛流程",
    main_category: "司内AI工具",
    info_type: "观点/分析",
    importance: "中",
    published_at: "2026-06-07T11:20:00Z",
    fetched_at: "2026-06-07T11:25:00Z",
    url: "https://example.com/internal-ai-triage",
    summary: "团队分享了把司内 AI 工具接入 release note 初筛的经验，重点是减少人工扫读时间。",
    key_points: [
      "[流程化] 以固定字段输出初筛结果",
      "[人工兜底] 保留人工复核入口",
      "[效率] 对周报整理效率提升明显",
    ],
    llm_confidence: 0.84,
    sub_tags: ["workflow", "release note"],
    source_links: [{ source_id: 4, url: "https://example.com/internal-ai-triage" }],
  },
];

export const demoFacets: Facets = {
  main_category: [],
  info_type: [],
  importance: [],
  sub_tags: [],
};
